database:
  name: ${DB_NAME:products}
spring:
  application:
    name: Products
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${database.name}
  liquibase:
    change-log: classpath:/liquibase/master.xml
    default-schema: ${database.name}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}?createDatabaseIfNotExist=true
    user: ${spring.datasource.username}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 9090

logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:info}
    com.vodafone.iot.products: ${APP_LOG_LEVEL:debug}
